### ISSUE TITLE
Run custom dataset

### ISSUE THREAD

**Issue by geokarant** [ivanpanshin/SupCon-Framework#31]
Hello everyone, I am trying to run  my own dataset, but I face the same error all the time. 

Traceback (most recent call last):
  File "train.py", line 64, in <module>
    loaders = utils.build_loaders(data_dir, transforms, batch_sizes, num_workers, second_stage=(stage == 'second'))
  File "/home/karantai/SupCon-Framework/tools/utils.py", line 93, in build_loaders
    transform=transforms['valid_transforms'], second_stage=True)
  File "/home/karantai/SupCon-Framework/tools/datasets.py", line 79, in create_supcon_dataset
    return DATASETS[dataset_name](data_dir, train, transform, second_stage)
  File "/home/karantai/SupCon-Framework/tools/datasets.py", line 50, in __init__
    super().__init__(root=data_dir, train=train, download=False, transform=transform)
  File "/home/karantai/anaconda3/envs/myenv/lib/python3.6/site-packages/torchvision/datasets/cifar.py", line 69, in __init__
    ' You can use download=True to download it')
RuntimeError: Dataset not found or corrupted. You can use download=True to download it

I have set Download = False. And I have created a pickled dict with my data as the cifar 10 is. Maybe my problem is trivial, but I would appreciate any help in utils.dataset.py modification or the dataset's layout. 

Thank you in advance guys!

**Comment by ivanpanshin** [comment]
Hey :) 

That's because it's trying to load the original cifar due to `super()` in `init` method. The simplest solution would be to add a new dataset based on examples in `utils/datasets.py`and add it to `DATASETS` variable
